export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_LOGIN_REQUEST_FAIL="USER_LOGIN_REQUEST_FAIL";
export const USER_LOGIN_REQUEST_SUCCESS="USER_LOGIN_REQUEST_SUCCESS";

export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST";
export const USER_REGISTER_REQUEST_FAIL="USER_REGISTER_REQUEST_FAIL";
export const USER_REGISTER_REQUEST_SUCCESS="USER_REGISTER_REQUEST_SUCCESS";
export const USER_LOG_OUT="USER_LOG_OUT";

export const USER_UPDATE_PROFILE_REQUEST="USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_REQUEST_FAIL="USER_UPDATE_PROFILE_REQUEST_FAIL";
export const USER_UPDATE_PROFILE_REQUEST_SUCCESS="USER_UPDATE_PROFILE_REQUEST_SUCCESS";
export const USER_UPDATE_PROFILE_REQUEST_RESET="USER_UPDATEPROFILE_REQUEST_RESET";

export const USER_LIST_REQUEST="USER_LIST_REQUEST";
export const USER_LIST_REQUEST_FAIL="USER_LIST_REQUEST_FAIL";
export const USER_LIST_REQUEST_SUCCESS="USER_LIST_REQUEST_SUCCESS";
export const USER_LIST_RESET="USER_LIST_RESET";


export const USER_DELETE_REQUEST="USER_DELETE_REQUEST";
export const USER_DELETE_REQUEST_FAIL="USER_DELETE_REQUEST_FAIL";
export const USER_DELETE_REQUEST_SUCCESS="USER_DELETE_REQUEST_SUCCESS";

export const USER_UPDATE_REQUEST="USER_UPDATE_REQUEST";
export const USER_UPDATE_REQUEST_FAIL="USER_UPDATE_REQUEST_FAIL";
export const USER_UPDATE_REQUEST_SUCCESS="USER_UPDATE_REQUEST_SUCCESS";
export const USER_UPDATE_RESET="USER_UPDATE_RESET";